coze-dev/coze-py

.github/workflows/ci.yml
cozepy/chat/__init__.py
cozepy/request.py
cozepy/workflows/runs/__init__.py
poetry.lock
pyproject.toml

- Update dependencies: requests -> httpx
- Refactor HTTP client code to use httpx

refactor: Replace requests with httpx

---

.gitignore
cozepy/__init__.py
cozepy/request.py
cozepy/version.py
poetry.lock
pyproject.toml
tests/test_version.py

- Created a version file to store the current SDK version
- Enhanced HTTP requests to include SDK version, language, and system version in the user-agent header
- Improved traceability and debugging with detailed user-agent information in requests

feat: Add version file and include in HTTP request user-agent

---

README.md
cozepy/__init__.py
cozepy/knowledge/documents/__init__.py
cozepy/workspaces/__init__.py

- Added usage instructions for knowledge document in README
- Exported knowledge related classes in `cozepy/__init__.py`
- Added two static methods to `DocumentChunkStrategy` and `DocumentUpdateRule` for quick creation

feat: Update documentation and export knowledge base classes

---

README.md
cozepy/__init__.py
cozepy/chat/__init__.py
cozepy/model.py
cozepy/workflows/runs/__init__.py
tests/test_chat.py
tests/test_workflow.py

- Merged `ChatChatIterator` and `WorkflowIterator` into a single generic Stream Iterator
- Unified iterator to support both Chat and Workflow module

refactor: Merge Chat and Workflow Iterator into a generic Stream Iterator

---

cozepy/request.py
tests/test_auth.py
tests/test_bot.py
tests/test_file.py

- Removed `get_args` and `get_origin` methods
- Replaced `List` with `Iterable` for simpler code

refactor: Simplify code by removing getargs and getorigin

---

cozepy/__init__.py
cozepy/auth/__init__.py

- Enhanced `JWTOAuthApp` to allow setting restrictions on specific bots during token request
- Improved security and control over bot interactions in the chat application

feat: Add bot restriction support in JWT OAuth app

---

README.md

- Documented usage instructions for 4 types of OAuth apps
- Included `WebOAuthApp`, `JWTOAuthApp`, `PKCEOAuthApp` and `DeviceOAuthApp`

docs: Add README for using 4 types of OAuth apps

---

README.md

- Fixed typo in README, changing 'pycon' to 'python'

docs: Correct typo in README from 'pycon' to 'python'

---

cozepy/__init__.py
cozepy/auth/__init__.py
cozepy/exception.py
cozepy/request.py
tests/test_auth.py
tests/test_exception.py

- Replaced `Literal["authorizationpending", "slowdown", "accessdenied", "expiredtoken"]` with `CozePKCEAuthErrorType Enum`
- Optimized type annotations for `CozePKCEAuthError`

refactor: Refactor CozePKCEAuthError to use CozePKCEAuthErrorType Enum

---

README.md
cozepy/bots/__init__.py

- Added instructions on how to use stream functionality
- Included guidelines for implementing async operations

docs: Update README to include usage instructions for stream and async

---

README.md
cozepy/chat/__init__.py
cozepy/model.py
cozepy/workflows/runs/__init__.py
tests/test_chat.py
tests/test_workflow.py

- Improved async iterator to function without requiring await

perf: Optimize async iterator to eliminate the need for await

---

README.md
cozepy/__init__.py
cozepy/bots/__init__.py
cozepy/conversations/message/__init__.py
cozepy/knowledge/documents/__init__.py
cozepy/model.py
cozepy/request.py
cozepy/workspaces/__init__.py
tests/test_bot.py
tests/test_conversation_message.py
tests/test_knowledge_documents.py
tests/test_model.py
tests/test_workflow.py
tests/test_workspace.py

- Added pagination iterator, support synchronous and asynchronous
- Enhanced paginator to support three usage methods:
1. Use paginator as a regular object, accessing T list via items attribute
2. Iterate over paginator to get T, ignoring pagination details and retrieving all data
3. Iterate over iter_pages method to get the paginator itself (i.e., handle pagination)

feat: Add iteration support to paginator

---

cozepy/__init__.py
cozepy/auth/__init__.py
cozepy/chat/__init__.py
cozepy/exception.py
cozepy/model.py
cozepy/workflows/runs/__init__.py
tests/test_chat.py
tests/test_exception.py
tests/test_model.py

- Implemented error handling for cases when `conversation.chat.failed` occurs
- Added ChatError to parse error messages
- Threw `CozeAPIError` exception when `conversation.chat.failed` is encountered
- Rename `CozeEventError` to `CozeInvalidEventError`

fix: Handle errors for chat.failed scenarios

---

cozepy/files/__init__.py
tests/test_file.py

- Modified upload file parameter type from str to Union[Path]
- Improved flexibility and usability of the upload function

refactor: Change upload file parameter from str to Union[Path]

---

README.md
cozepy/auth/__init__.py
cozepy/chat/__init__.py
cozepy/files/__init__.py
cozepy/knowledge/documents/__init__.py
pyproject.toml
tests/test_auth.py
tests/test_chat.py
tests/test_chat_message.py
tests/test_conversation_message.py
tests/test_knowledge_documents.py

- Renamed class static methods to consistently start with build
- Set default expiration time of 900s for jwt oauth token
- Added default empty string value for state parameter in `OAuthApp`
- Modified some fields in `CozeModel` to be optional
- Added `create_and_poll` method to encapsulate chat.create and chat.retrieve

refactor: Standardize and enhance various components

---

cozepy/chat/__init__.py

- Fixed `build_user_question_objects` method to change content_type from `text` to `object_string`
- Related Issue: https://github.com/coze-dev/coze-py/issues/84

fix: Fix `build_user_question_objects` method in Message

---

cozepy/chat/__init__.py

- Updated field name from 'argument' to 'arguments' in `ChatToolCallFunction`

fix: Fix field name in ChatToolCallFunction from 'argument' to 'arguments'

---

cozepy/request.py

- Fixed issue with `response.json` raising `httpx.ResponseNotRead` in stream mode
- Non-stream mode defaults to `response.read` as expected
- Stream mode with correct response uses `iter_lines` without issues
- Stream mode with errors (e.g., token errors) now handled properly

fix: Resolve httpx.ResponseNotRead error in stream mode

---

cozepy/__init__.py
cozepy/auth/__init__.py
cozepy/chat/__init__.py
cozepy/conversations/__init__.py
cozepy/model.py
examples/conversation_list.py
tests/test_auth.py
tests/test_conversation.py

- Supported binding bot_id when creating a conversation
- Added get the list of conversations bound to bot_id
- Added clear a conversation and returned a new section
- Added bind session_name during JWT token creation

feat: Add conversation management APIs

---

cozepy/chat/__init__.py

- Move conversation_id from request body to query parameters

fix: Correct conversation_id parameter placement in chat API

---

cozepy/chat/__init__.py

- Changed chat.cancel API to accept parameters in request body instead of query params

fix: Update chat.cancel API to use body instead of params

---

cozepy/__init__.py
cozepy/coze.py
cozepy/templates/__init__.py
examples/cli.py
examples/template_duplicate.py
tests/test_template.py

- Add new API endpoint for template duplicate functionality
- Implement unit tests to ensure reliability of the new feature
- Create usage examples to demonstrate the template copying process

feat: Implement template duplicate API with tests and examples

---

cozepy/auth/__init__.py

- Add timestamp and OS entropy sources to JTI generation to prevent duplication when users set fixed random seeds
- Use {timestamp}:{random_hex(8)}:{os.urandom(8).hex()} combination to ensure uniqueness
- Resolve JWT token security vulnerability that could be compromised by predictable random numbers

fix: JWT JTI generation security issue with fixed random seed
