- .github/workflows/ci.yml
- CONTRIBUTING.md
- README.md
- codecov.yml
- cozepy/auth/__init__.py
- cozepy/chat/__init__.py
- poetry.lock
- pyproject.toml
- Added coverage.io configuration to the project
- Updated ci.yaml to include coverage reporting
- Added coverage badge to README for visual representation of test coverage
> chore: Configure coverage.io and update ci.yaml

- cozepy/__init__.py
- cozepy/config.py
- cozepy/coze.py
- cozepy/request.py
- cozepy/util.py
- Created a custom `HTTPClient` class that inherits from `httpx.Client`
- Overridden default parameters such as timeout configuration
- Adjusted connection pool settings for better performance and control
> feat: Customize HTTPClient by extending httpx.Client

- cozepy/coze.py
- cozepy/knowledge/__init__.py
- cozepy/knowledge/documents/__init__.py
- cozepy/version.py
- tests/test_knowledge.py
- Implemented an API to retrieve document lists from a specified knowledge base
> feat: Add Knowledge API to fetch document list

- README.md
- cozepy/__init__.py
- cozepy/auth/__init__.py
- cozepy/bots/__init__.py
- cozepy/chat/__init__.py
- cozepy/config.py
- cozepy/conversations/__init__.py
- cozepy/conversations/message/__init__.py
- cozepy/coze.py
- cozepy/knowledge/__init__.py
- cozepy/knowledge/documents/__init__.py
- cozepy/model.py
- cozepy/request.py
- cozepy/workflows/runs/__init__.py
- cozepy/workspaces/__init__.py
- pyproject.toml
- tests/config.py
- tests/test_chat.py
- tests/test_conversation_message.py
- Changed all enum values from lowercase to uppercase snake_case to comply with Python conventions
- Modified ruff configuration for code formatting
> style: Update enum values to uppercase snake_case and format code

- cozepy/__init__.py
- cozepy/log.py
- cozepy/request.py
- Added logging to requester requests
- Introduced `setup_logging` function to configure log levels
- Improved monitoring and debugging capabilities through enhanced logging
> feat: Add logging to requester and setup_logging function

- cozepy/knowledge/documents/__init__.py
- Fixed the method and parameters for retrieving the knowledge base document list
> fix: Correct knowledge base document list retrieval API

- cozepy/auth/__init__.py
- cozepy/request.py
- cozepy/util.py
- tests/test_chat.py
- Relocated random_hex function to the util.py
- Improved code organization by centralizing utility functions
> refactor: Move random_hex function to util.py

- cozepy/__init__.py
- cozepy/auth/__init__.py
- cozepy/util.py
- tests/config.py
- tests/test_auth.py
- Implemented PKCE OAuth flow including authorization url generation, code-to-token exchange, and token refresh
- Refactored JWT OAuth by creating a common OAuthApp base class
- Ensured both PKCE OAuth app and JWT OAuth app inherit from the new OAuthApp base class for improved code reuse and maintainability
> feat: Add PKCE OAuth flow and refactor OAuth structure

- cozepy/__init__.py
- cozepy/auth/__init__.py
- cozepy/exception.py
- cozepy/request.py
- Implemented device auth flow including obtaining device code, token exchange, and token refresh
- Added support for handling PKCE flow errors like `authorization_pending`, `slow_down`, `access_denied` and `expired_token`
> feat: Add Device Auth flow with error handling

- cozepy/auth/__init__.py
- Fixed the scope parameter type issue in JWT OAuth app when used in channel scenarios
> fix: Correct scope parameter type in JWT OAuth app for channel scenarios

- cozepy/__init__.py
- cozepy/auth/__init__.py
- Implemented Web OAuth app scenario supporting auth URL generation
- Added functionality to exchange auth code for token and refresh token
> feat: Add Web OAuth app scenario

- cozepy/conversations/__init__.py
- cozepy/request.py
- tests/test_auth.py
- tests/test_chat.py
- tests/test_chat_message.py
- tests/test_conversation.py
- tests/test_conversation_message.py
- tests/test_exception.py
- tests/test_knowledge_documents.py
- tests/test_log.py
- tests/test_workflow.py
- tests/test_workspace.py
- Increase coverage for existing modules
> chore: Add more test

- codecov.yml
- cozepy/auth/__init__.py
- cozepy/exception.py
- cozepy/model.py
- pyproject.toml
- tests/test_auth.py
- tests/test_chat.py
- tests/test_model.py
- tests/test_request.py
- tests/test_workflow.py
- Modified pyproject codecov configuration to skip TYPE_CHECKING sections from coverage calculation
- Updated codecov configuration to only check coverage for the cozepy directory
- Added missing unit tests to improve overall test coverage
> chore: Update codecov configuration and add missing unit tests

- cozepy/chat/__init__.py
- cozepy/exception.py
- cozepy/model.py
- cozepy/request.py
- cozepy/workflows/runs/__init__.py
- tests/test_exception.py
- tests/test_model.py
- Enhanced CozeEventError to include logid for better traceability
> feat: Add logid support to CozeEventError exception

- cozepy/version.py
- pyproject.toml
> chore: Release v0.2.0

- .gitignore
- codecov.yml
- cozepy/__init__.py
- cozepy/coze.py
- cozepy/request.py
- poetry.lock
- pyproject.toml
- tests/test_request.py
- Added arequest method to Requester with httpx.AsyncClient to support async requests
- Integrated pytest-asyncio to enable testing of arequest async function
- Renamed HTTPClient to SyncHTTPClient and add AsyncHTTPClient for clarity
> feat: Add async support with httpx.AsyncClient and refactor HTTP clients

- cozepy/chat/message/__init__.py
- cozepy/knowledge/documents/__init__.py
- cozepy/request.py
- Fixed type annotation issue to correctly recognize model's Iterable type
- Ensured proper unpacking of sub-elements within the Iterable
> chore: Correct type annotation to accurately identify

- cozepy/version.py
- pyproject.toml
> chore: Release v0.3.0

- cozepy/version.py
- pyproject.toml
> chore: Release v0.4.0

- README.md
- cozepy/knowledge/documents/__init__.py
- examples/auth_oauth_device.py
- examples/auth_oauth_jwt.py
- examples/auth_oauth_pkce.py
- examples/auth_oauth_web.py
- examples/auth_pat.py
- examples/bot_publish.py
- examples/chat_multimode_stream.py
- examples/chat_no_stream.py
- examples/chat_stream.py
- examples/exception.py
- examples/log.py
- examples/workflow_no_stream.py
- examples/workflow_stream.py
- tests/test_knowledge_documents.py
- Created an examples directory to organize usage examples
- Synchronized examples with the README for better accessibility
> docs: Add examples directory and update README

- README.md
- cozepy/version.py
- pyproject.toml
> chore: Release v0.5.0

- examples/chat_multimode_stream.py
- poetry.lock
- pyproject.toml
- Fixed compatibility issues with httpx in higher Python versions
> fix: Resolve dependency issue with httpx in higher Python versions

- README.md
- examples/auth_oauth_device.py
- examples/auth_oauth_jwt.py
- examples/auth_oauth_pkce.py
- examples/auth_oauth_web.py
- examples/auth_pat.py
- examples/bot_publish.py
- examples/chat_multimode_stream.py
- examples/chat_no_stream.py
- examples/chat_stream.py
- examples/exception.py
- examples/workflow_no_stream.py
- examples/workflow_stream.py
- tests/test_workspace.py
- Updated README to include details on setting base_url
- Added examples demonstrating how to configure base_url
> docs: Add instructions for setting base_url in examples and README

- README.md
- examples/timeout.py
- Updated README with instructions on how to configure timeout
- Added examples demonstrating timeout configuration
> docs: Add examples and README instructions for configuring timeout

- cozepy/request.py
- examples/chat_multimode_stream.py
- examples/chat_no_stream.py
- examples/chat_stream.py
- Fixed issues in chat.stream api
- Ensured proper handling of streaming data
> fix: Fix chat.stream api for streaming responses

- cozepy/version.py
- pyproject.toml
> chore: Release v0.6.1

- cozepy/chat/__init__.py
- cozepy/version.py
- examples/chat_conversation_stream.py
- pyproject.toml
- Fixed issues with conversation parameter passing in `chat.create` and `chat.stream`
- Added a translation example to demonstrate how to use conversation
- Updated version to v0.6.2
> fix: Fix chat api conversation parameter and Release v0.6.2

- cozepy/__init__.py
- cozepy/coze.py
- cozepy/rooms/__init__.py
- tests/test_room.py
- Implemented API for creating a room
- Added unit tests for creating a room functionality
- Exported `CreateRoomResult` for external use
> feat: Add API for creating room

- examples/auth_oauth_jwt.py
- Added steps for reading private key from a file
- Added docs for ttl usage
> docs: Update JWT OAuth usage example

- README.md
- cozepy/__init__.py
- cozepy/request.py
- cozepy/workflows/runs/__init__.py
- cozepy/workflows/runs/run_histories/__init__.py
- examples/workflow_async.py
- tests/test_workflow.py
- Added is_async for asynchronous workflow execution
- Added API to retrieve execution history of async workflows
- Updated example and README with workflow async usage details
> feat: Add async execution to workflow and history retrieval

- README.md
- cozepy/chat/__init__.py
- cozepy/conversations/__init__.py
- examples/conversation.py
- tests/test_conversation.py
- Added last_section_id field to the conversation structure
- Added section_id field to the message structure
- Updated related documentation and tests to include section_id
> feat: Add section_id field to conversation and message structures

- cozepy/__init__.py
- cozepy/audio/__init__.py
- cozepy/audio/voices/__init__.py
- cozepy/bots/__init__.py
- cozepy/knowledge/documents/__init__.py
- cozepy/model.py
- cozepy/workspaces/__init__.py
- examples/audio.py
- tests/test_audio_voices.py
- Added an API to retrieve the list of voices
- Upgraded NumberPaged to support returning has_more field
- Updated related documentation and tests to reflect these changes
> feat: Add voice list retrieval API and upgrade NumberPaged

- cozepy/audio/__init__.py
- cozepy/audio/rooms/__init__.py
- cozepy/audio/speech/__init__.py
- cozepy/audio/voices/__init__.py
- cozepy/auth/__init__.py
- cozepy/bots/__init__.py
- cozepy/chat/__init__.py
- cozepy/chat/message/__init__.py
- cozepy/conversations/__init__.py
- cozepy/conversations/message/__init__.py
- cozepy/coze.py
- cozepy/files/__init__.py
- cozepy/knowledge/__init__.py
- cozepy/knowledge/documents/__init__.py
- cozepy/util.py
- cozepy/workflows/__init__.py
- cozepy/workflows/runs/__init__.py
- cozepy/workflows/runs/run_histories/__init__.py
- cozepy/workspaces/__init__.py
- tests/test_util.py
- Removed trailing slash from base_url configuration to prevent user configuration errors
> perf: Optimize base_url configuration by removing trailing slash

- README.md
- examples/auth_oauth_device.py
- examples/workspace.py
- Added example usage for the workspace list API
- Updated README to include documentation for the workspace list API example
> docs: Add example for workspace list API

- cozepy/auth/__init__.py
- examples/auth_oauth_jwt.py
- Updated JWTAuth to directly accept a JWTOAuthApp instance rather than its constructor parameters
- Modified the JWT OAuth examples to provide more user-friendly code samples
> feat: Enhance JWTAuth to Support Direct JWTOAuthApp Instance && Opt Examples

- .vscode/settings.json
- Created `.vscode/settings.json` file for project-specific VSCode settings
- Configured editor settings to maintain consistent coding style
> chore: Add VSCode settings configuration file

- cozepy/audio/speech/__init__.py
- tests/test_audio_speech.py
- Implement support for sample_rate parameter in audio speech api
- Allow users to specify desired sample rate for audio output
> feat: Add sample_rate parameter support to audio speech API

- .coderabbit.yaml
- cozepy/chat/__init__.py
- cozepy/model.py
- cozepy/request.py
- cozepy/workflows/runs/__init__.py
- cozepy/workflows/runs/run_histories/__init__.py
- tests/test_audio_rooms.py
- tests/test_audio_speech.py
- tests/test_audio_voices.py
- tests/test_bots.py
- tests/test_chat.py
- tests/test_conversations.py
- tests/test_conversations_messages.py
- tests/test_datasets_documents.py
- tests/test_file.py
- tests/test_model.py
- tests/test_util.py
- tests/test_workflows.py
- Replace hardcoded logid with dynamic retrieval from httpx.Response
- Implement new method to extract logid from response headers or body
- Update coderabbit config to disable auto modify MR title & desc
> refactor: Enhance logid implementation using httpx.Response properties

- cozepy/files/__init__.py
- examples/cli.py
- tests/test_file.py
- Add support for Path and str type file paths
- Add support for directly specify filename and content
> feat: Enhance file upload with multiple parameter options

- cozepy/model.py
- cozepy/request.py
- cozepy/workflows/runs/run_histories/__init__.py
- tests/test_audio_rooms.py
- tests/test_audio_speech.py
- tests/test_audio_translations.py
- tests/test_audio_voices.py
- tests/test_bots.py
- tests/test_chat.py
- tests/test_chat_messages.py
- tests/test_conversations.py
- tests/test_conversations_messages.py
- tests/test_datasets.py
- tests/test_datasets_documents.py
- tests/test_datasets_images.py
- tests/test_file.py
- tests/test_workflows.py
- Implement 'response' property on all returned objects to access HTTPResponse
- Add 'logid' property to HTTPResponse for consistent logid access
- Update all existing code to use new logid access pattern
- Update unit tests to verify correct logid access through HTTPResponse
> refactor: Restructure logid system for unified access through HTTPResponse

- README.md
- cozepy/chat/__init__.py
- cozepy/model.py
- cozepy/request.py
- cozepy/util.py
- cozepy/workflows/__init__.py
- cozepy/workflows/chat/__init__.py
- examples/workflow_chat_stream.py
- tests/test_workflows_chat.py
- tests/testdata/workflows_chat_stream_resp.txt
- Added new workflow chat API endpoints
- Added Unit  Test and Examples
> feat: Add workflow chat API with tests and usage examples

- cozepy/version.py
- cozepy/workflows/chat/__init__.py
- pyproject.toml
- Change parameters type annotation from Optional[Dict[str, str]] to Optional[Dict[str, Any]]
- Bump version to 0.9.1
> chore: Update parameters type annotation in workflows.chat and Bump version to 0.9.1

- cozepy/audio/voices/__init__.py
- tests/test_audio_voices.py
- Update file type to FileTypes in voices.clone
- Add optional space_id and description parameters in voices.clone
- Add Unit Test
> feat: Add description and space_id parameters to voices.clone api
